version: '3'

services:
  ms-logistica-pedidos:
    image: 'ms-logistica-pedidos:dev'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms-logistica-pedidos
    depends_on:
      - db-logistica
    ports:
      - "8083:8080"
    environment:
      - DB_HOST=db-logistica
      - DB_PORT=5432
      - DB_NAME=ms-logistica-pedidos
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    networks:
      - shared_network

  db-logistica:
    image: postgres
    container_name: logistica-pedidos-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ms-logistica-pedidos
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_logistica:/var/lib/postgresql/data
    networks:
      - shared_network


volumes:
  postgres_data_logistica:

networks:
  shared_network:
    driver: bridge
    external: true
