version: '3'

services:
  ms-logistica-pedidos:
    image: 'ms-logistica-pedidos:dev'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms-logistica-pedidos
    depends_on:
      - db-logistica
      - ms-gestao-pedidos
    ports:
      - "8083:8081"
    environment:
      - DB_HOST=db-logistica
      - DB_PORT=5432
      - DB_NAME=ms-logistica-pedidos
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    networks:
      - app_network

  db-logistica:
    image: postgres
    container_name: logistica-pedidos-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ms-logistica-pedidos
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_logistica:/var/lib/postgresql/data
    networks:
      - app_network

  db-pedidos:
    image: postgres
    container_name: gestao-pedidos-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ms-gestao-pedidos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_pedidos:/var/lib/postgresql/data
    networks:
      - app_network

  ms-gestao-pedidos:
    image: ms-gestao-pedidos:dev
    container_name: ms-gestao-pedidos
    depends_on:
      - db-pedidos
    networks:
      - app_network
    ports:
      - "8081:8080"
    environment:
      - DB_HOST=db-pedidos
      - DB_PORT=5432
      - DB_NAME=ms-gestao-pedidos
      - DB_USERNAME=root
      - DB_PASSWORD=secret

volumes:
  postgres_data_logistica:
  postgres_data_pedidos:

networks:
  app_network:
    driver: bridge
